name: Final Project 

on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Greet & Count the files
        env:
          STUDENT_NAME: ${{ vars.website }}
        run: |
          COUNT=$(find . -type f -not -path './.git/*' | wc -l)
          echo "Hello, ${{ env. website}}, your files count is $COUNT"